apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    app.kubernetes.io/name: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: blockchain
  labels:
    app.kubernetes.io/name: blockchain
